Repository cmc-haskell-2018/straminata, pull requests merged in 2018-02, with the labels that each got.

#1 Review experimental changes in Experimental_1
  src/Model/CommonTypes.hs
  src/Straminata.hs
  src/Util/Common.hs
  straminata.cabal
Labels: enhancement, help wanted

#25 Feature/issue5 add collisions
  src/Controls.hs
  src/Model/CommonTypes.hs
  src/Straminata.hs
  src/Util/Common.hs
  src/Visual/Renderer.hs
  straminata.cabal
  test/Spec.hs
Labels: basic task, enhancement, help wanted

#28 Add Utils.Common module documentation
  src/Util/Common.hs
Labels: minor

#29 Feature/player controls enhancement
  src/Controls.hs
  src/Model/CommonTypes.hs
  src/Straminata.hs
Labels: basic task, enhancement

#39 Refactor/rename record functions
  src/Controls.hs
  src/Model/CommonTypes.hs
  src/Straminata.hs
  src/Util/Common.hs
  src/Visual/Renderer.hs
Labels: refactor

#41 Refactor/create event listeners 2
  src/Controls.hs
  src/Model/CommonTypes.hs
  src/Straminata.hs
Labels: experimental, refactor

#42 Feature/refactor common types
  src/Model/CommonTypes.hs
  src/Straminata.hs
  src/Util/Common.hs
  src/Visual/Renderer.hs
  test/Spec.hs
Labels: basic task, critical, refactor

#49 Fix the bug with camera and appearance pictures
  src/Util/Common.hs
  src/Visual/Renderer.hs
Labels: bug

#56 Feature/map representation 2
  img/background.png
  src/Controls.hs
  src/Model/CommonTypes.hs
  src/Model/Map.hs
  src/Straminata.hs
  src/Visual/Renderer.hs
  src/Visual/TextureLoader.hs
Labels: enhancement
